version: '3'

services:
  apache2:
    container_name: apache2-tcc
    build: ./
    ports:
      - "8070:80"
    volumes: 
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    container_name: mysql-tcc
    image: eriktonon/mysql:5.7.27
    ports:
      - "3308:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./database/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    env_file: 
      - .env-mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
